github:
  release: true
git:
  changelog: "git log --pretty=format:\"* %s (%h)\" ${from}...${to}"
  commitMessage: "Release ${version}"
  tag: true
  tagAnnotation: "Release ${version}"
npm:
  publish: false
hooks:
  before:init:
    - "yarn test"
    - "yarn run test-contract-bindings"
    - "yarn run test-api-bindings"
  after:release:
    - "echo Successfully released ${name} v${version} to ${repo.repository}."
plugins:
  "@release-it/keep-a-changelog":
    filename: "CHANGELOG.md"