/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface RegistrationV2Interface extends utils.Interface {
  functions: {
    "imx()": FunctionFragment;
    "isRegistered(uint256)": FunctionFragment;
    "registerAndWithdrawAll(address,uint256,bytes,uint256)": FunctionFragment;
    "withdrawAll(uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "imx"
      | "isRegistered"
      | "registerAndWithdrawAll"
      | "withdrawAll"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "imx", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAndWithdrawAll",
    values: [string, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAll",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "imx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAndWithdrawAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAll",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RegistrationV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RegistrationV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    imx(overrides?: CallOverrides): Promise<[string]>;

    isRegistered(
      starkKey: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    registerAndWithdrawAll(
      ethKey: string,
      starkKey: BigNumberish,
      signature: BytesLike,
      assetType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawAll(
      ethKey: BigNumberish,
      starkKey: BigNumberish,
      assetType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  imx(overrides?: CallOverrides): Promise<string>;

  isRegistered(
    starkKey: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  registerAndWithdrawAll(
    ethKey: string,
    starkKey: BigNumberish,
    signature: BytesLike,
    assetType: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawAll(
    ethKey: BigNumberish,
    starkKey: BigNumberish,
    assetType: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    imx(overrides?: CallOverrides): Promise<string>;

    isRegistered(
      starkKey: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registerAndWithdrawAll(
      ethKey: string,
      starkKey: BigNumberish,
      signature: BytesLike,
      assetType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAll(
      ethKey: BigNumberish,
      starkKey: BigNumberish,
      assetType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    imx(overrides?: CallOverrides): Promise<BigNumber>;

    isRegistered(
      starkKey: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerAndWithdrawAll(
      ethKey: string,
      starkKey: BigNumberish,
      signature: BytesLike,
      assetType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawAll(
      ethKey: BigNumberish,
      starkKey: BigNumberish,
      assetType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    imx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isRegistered(
      starkKey: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerAndWithdrawAll(
      ethKey: string,
      starkKey: BigNumberish,
      signature: BytesLike,
      assetType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawAll(
      ethKey: BigNumberish,
      starkKey: BigNumberish,
      assetType: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
