/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { LambdasAPIError } from '../models';
// @ts-ignore
import { NftsecondarytransactionCreateAPIRequest } from '../models';
// @ts-ignore
import { NftsecondarytransactionCreateResponse } from '../models';
// @ts-ignore
import { NftsecondarytransactionGetTransactionResponse } from '../models';
// @ts-ignore
import { NftsecondarytransactionListTransactionsResponse } from '../models';
/**
 * NftCheckoutSecondaryApi - axios parameter creator
 * @export
 */
export const NftCheckoutSecondaryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * creates nft secondary transaction
         * @summary Create nft secondary transaction
         * @param {NftsecondarytransactionCreateAPIRequest} createAPIRequest req
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNftSecondary: async (createAPIRequest: NftsecondarytransactionCreateAPIRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAPIRequest' is not null or undefined
            assertParamExists('createNftSecondary', 'createAPIRequest', createAPIRequest)
            const localVarPath = `/v2/nft/secondary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAPIRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * gets nft secondary transaction by transaction id
         * @summary Get nft secondary transaction by id
         * @param {string} transactionId Transaction id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNftSecondaryTransaction: async (transactionId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transactionId' is not null or undefined
            assertParamExists('getNftSecondaryTransaction', 'transactionId', transactionId)
            const localVarPath = `/v2/nft/secondary/{transaction_id}`
                .replace(`{${"transaction_id"}}`, encodeURIComponent(String(transactionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of NFT secondary transactions
         * @summary Get a list of NFT secondary transactions
         * @param {number} [pageSize] Page size of the result
         * @param {string} [cursor] Cursor
         * @param {'transaction_id' | 'status' | 'amount' | 'mint_id'} [orderBy] Property to sort by
         * @param {string} [direction] Direction to sort (asc/desc)
         * @param {string} [transactionId] Transaction id
         * @param {number} [orderId] Order id
         * @param {string} [walletAddress] Ethereum address of the user who wants to create transaction
         * @param {string} [status] Transaction status
         * @param {'moonpay'} [provider] Provider name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNftSecondaryTransactions: async (pageSize?: number, cursor?: string, orderBy?: 'transaction_id' | 'status' | 'amount' | 'mint_id', direction?: string, transactionId?: string, orderId?: number, walletAddress?: string, status?: string, provider?: 'moonpay', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/nft/secondary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['order_by'] = orderBy;
            }

            if (direction !== undefined) {
                localVarQueryParameter['direction'] = direction;
            }

            if (transactionId !== undefined) {
                localVarQueryParameter['transaction_id'] = transactionId;
            }

            if (orderId !== undefined) {
                localVarQueryParameter['order_id'] = orderId;
            }

            if (walletAddress !== undefined) {
                localVarQueryParameter['wallet_address'] = walletAddress;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (provider !== undefined) {
                localVarQueryParameter['provider'] = provider;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NftCheckoutSecondaryApi - functional programming interface
 * @export
 */
export const NftCheckoutSecondaryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NftCheckoutSecondaryApiAxiosParamCreator(configuration)
    return {
        /**
         * creates nft secondary transaction
         * @summary Create nft secondary transaction
         * @param {NftsecondarytransactionCreateAPIRequest} createAPIRequest req
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNftSecondary(createAPIRequest: NftsecondarytransactionCreateAPIRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NftsecondarytransactionCreateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNftSecondary(createAPIRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * gets nft secondary transaction by transaction id
         * @summary Get nft secondary transaction by id
         * @param {string} transactionId Transaction id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNftSecondaryTransaction(transactionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NftsecondarytransactionGetTransactionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNftSecondaryTransaction(transactionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a list of NFT secondary transactions
         * @summary Get a list of NFT secondary transactions
         * @param {number} [pageSize] Page size of the result
         * @param {string} [cursor] Cursor
         * @param {'transaction_id' | 'status' | 'amount' | 'mint_id'} [orderBy] Property to sort by
         * @param {string} [direction] Direction to sort (asc/desc)
         * @param {string} [transactionId] Transaction id
         * @param {number} [orderId] Order id
         * @param {string} [walletAddress] Ethereum address of the user who wants to create transaction
         * @param {string} [status] Transaction status
         * @param {'moonpay'} [provider] Provider name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNftSecondaryTransactions(pageSize?: number, cursor?: string, orderBy?: 'transaction_id' | 'status' | 'amount' | 'mint_id', direction?: string, transactionId?: string, orderId?: number, walletAddress?: string, status?: string, provider?: 'moonpay', options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NftsecondarytransactionListTransactionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNftSecondaryTransactions(pageSize, cursor, orderBy, direction, transactionId, orderId, walletAddress, status, provider, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * NftCheckoutSecondaryApi - factory interface
 * @export
 */
export const NftCheckoutSecondaryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NftCheckoutSecondaryApiFp(configuration)
    return {
        /**
         * creates nft secondary transaction
         * @summary Create nft secondary transaction
         * @param {NftsecondarytransactionCreateAPIRequest} createAPIRequest req
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNftSecondary(createAPIRequest: NftsecondarytransactionCreateAPIRequest, options?: any): AxiosPromise<NftsecondarytransactionCreateResponse> {
            return localVarFp.createNftSecondary(createAPIRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * gets nft secondary transaction by transaction id
         * @summary Get nft secondary transaction by id
         * @param {string} transactionId Transaction id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNftSecondaryTransaction(transactionId: string, options?: any): AxiosPromise<NftsecondarytransactionGetTransactionResponse> {
            return localVarFp.getNftSecondaryTransaction(transactionId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of NFT secondary transactions
         * @summary Get a list of NFT secondary transactions
         * @param {number} [pageSize] Page size of the result
         * @param {string} [cursor] Cursor
         * @param {'transaction_id' | 'status' | 'amount' | 'mint_id'} [orderBy] Property to sort by
         * @param {string} [direction] Direction to sort (asc/desc)
         * @param {string} [transactionId] Transaction id
         * @param {number} [orderId] Order id
         * @param {string} [walletAddress] Ethereum address of the user who wants to create transaction
         * @param {string} [status] Transaction status
         * @param {'moonpay'} [provider] Provider name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNftSecondaryTransactions(pageSize?: number, cursor?: string, orderBy?: 'transaction_id' | 'status' | 'amount' | 'mint_id', direction?: string, transactionId?: string, orderId?: number, walletAddress?: string, status?: string, provider?: 'moonpay', options?: any): AxiosPromise<NftsecondarytransactionListTransactionsResponse> {
            return localVarFp.getNftSecondaryTransactions(pageSize, cursor, orderBy, direction, transactionId, orderId, walletAddress, status, provider, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createNftSecondary operation in NftCheckoutSecondaryApi.
 * @export
 * @interface NftCheckoutSecondaryApiCreateNftSecondaryRequest
 */
export interface NftCheckoutSecondaryApiCreateNftSecondaryRequest {
    /**
     * req
     * @type {NftsecondarytransactionCreateAPIRequest}
     * @memberof NftCheckoutSecondaryApiCreateNftSecondary
     */
    readonly createAPIRequest: NftsecondarytransactionCreateAPIRequest
}

/**
 * Request parameters for getNftSecondaryTransaction operation in NftCheckoutSecondaryApi.
 * @export
 * @interface NftCheckoutSecondaryApiGetNftSecondaryTransactionRequest
 */
export interface NftCheckoutSecondaryApiGetNftSecondaryTransactionRequest {
    /**
     * Transaction id
     * @type {string}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransaction
     */
    readonly transactionId: string
}

/**
 * Request parameters for getNftSecondaryTransactions operation in NftCheckoutSecondaryApi.
 * @export
 * @interface NftCheckoutSecondaryApiGetNftSecondaryTransactionsRequest
 */
export interface NftCheckoutSecondaryApiGetNftSecondaryTransactionsRequest {
    /**
     * Page size of the result
     * @type {number}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly pageSize?: number

    /**
     * Cursor
     * @type {string}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly cursor?: string

    /**
     * Property to sort by
     * @type {'transaction_id' | 'status' | 'amount' | 'mint_id'}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly orderBy?: 'transaction_id' | 'status' | 'amount' | 'mint_id'

    /**
     * Direction to sort (asc/desc)
     * @type {string}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly direction?: string

    /**
     * Transaction id
     * @type {string}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly transactionId?: string

    /**
     * Order id
     * @type {number}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly orderId?: number

    /**
     * Ethereum address of the user who wants to create transaction
     * @type {string}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly walletAddress?: string

    /**
     * Transaction status
     * @type {string}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly status?: string

    /**
     * Provider name
     * @type {'moonpay'}
     * @memberof NftCheckoutSecondaryApiGetNftSecondaryTransactions
     */
    readonly provider?: 'moonpay'
}

/**
 * NftCheckoutSecondaryApi - object-oriented interface
 * @export
 * @class NftCheckoutSecondaryApi
 * @extends {BaseAPI}
 */
export class NftCheckoutSecondaryApi extends BaseAPI {
    /**
     * creates nft secondary transaction
     * @summary Create nft secondary transaction
     * @param {NftCheckoutSecondaryApiCreateNftSecondaryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NftCheckoutSecondaryApi
     */
    public createNftSecondary(requestParameters: NftCheckoutSecondaryApiCreateNftSecondaryRequest, options?: AxiosRequestConfig) {
        return NftCheckoutSecondaryApiFp(this.configuration).createNftSecondary(requestParameters.createAPIRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * gets nft secondary transaction by transaction id
     * @summary Get nft secondary transaction by id
     * @param {NftCheckoutSecondaryApiGetNftSecondaryTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NftCheckoutSecondaryApi
     */
    public getNftSecondaryTransaction(requestParameters: NftCheckoutSecondaryApiGetNftSecondaryTransactionRequest, options?: AxiosRequestConfig) {
        return NftCheckoutSecondaryApiFp(this.configuration).getNftSecondaryTransaction(requestParameters.transactionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of NFT secondary transactions
     * @summary Get a list of NFT secondary transactions
     * @param {NftCheckoutSecondaryApiGetNftSecondaryTransactionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NftCheckoutSecondaryApi
     */
    public getNftSecondaryTransactions(requestParameters: NftCheckoutSecondaryApiGetNftSecondaryTransactionsRequest = {}, options?: AxiosRequestConfig) {
        return NftCheckoutSecondaryApiFp(this.configuration).getNftSecondaryTransactions(requestParameters.pageSize, requestParameters.cursor, requestParameters.orderBy, requestParameters.direction, requestParameters.transactionId, requestParameters.orderId, requestParameters.walletAddress, requestParameters.status, requestParameters.provider, options).then((request) => request(this.axios, this.basePath));
    }
}
