/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSignableTradeResponse
 */
export interface GetSignableTradeResponse {
    /**
     * Amount to buy
     * @type {string}
     * @memberof GetSignableTradeResponse
     */
    'amount_buy'?: string;
    /**
     * Amount to sell
     * @type {string}
     * @memberof GetSignableTradeResponse
     */
    'amount_sell'?: string;
    /**
     * ID of the asset to buy
     * @type {string}
     * @memberof GetSignableTradeResponse
     */
    'asset_id_buy'?: string;
    /**
     * ID of the asset to sell
     * @type {string}
     * @memberof GetSignableTradeResponse
     */
    'asset_id_sell'?: string;
    /**
     * Expiration timestamp for this order
     * @type {number}
     * @memberof GetSignableTradeResponse
     */
    'expiration_timestamp'?: number;
    /**
     * Nonce of the order
     * @type {number}
     * @memberof GetSignableTradeResponse
     */
    'nonce'?: number;
    /**
     * Payload Hash
     * @type {string}
     * @memberof GetSignableTradeResponse
     */
    'payload_hash'?: string;
    /**
     * Public stark key of the created user
     * @type {string}
     * @memberof GetSignableTradeResponse
     */
    'stark_key'?: string;
    /**
     * ID of the vault into which the bought asset will be placed
     * @type {number}
     * @memberof GetSignableTradeResponse
     */
    'vault_id_buy'?: number;
    /**
     * ID of the vault to sell from
     * @type {number}
     * @memberof GetSignableTradeResponse
     */
    'vault_id_sell'?: number;
}

