/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSnapshotRequest
 */
export interface GetSnapshotRequest {
    /**
     * List of ether keys
     * @type {Array<string>}
     * @memberof GetSnapshotRequest
     */
    'ether_keys'?: Array<string>;
}

