/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Reward
 */
export interface Reward {
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    'ether_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    'expiration_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    'points'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Reward
     */
    'token_address'?: string;
}

