/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TradeSide } from './trade-side';

/**
 * 
 * @export
 * @interface Trade
 */
export interface Trade {
    /**
     * 
     * @type {TradeSide}
     * @memberof Trade
     */
    'a'?: TradeSide;
    /**
     * 
     * @type {TradeSide}
     * @memberof Trade
     */
    'b'?: TradeSide;
    /**
     * Status of this trade
     * @type {string}
     * @memberof Trade
     */
    'status'?: string;
    /**
     * Time this trade occurred
     * @type {string}
     * @memberof Trade
     */
    'timestamp'?: string;
    /**
     * Sequential ID of this trade within Immutable X
     * @type {number}
     * @memberof Trade
     */
    'transaction_id'?: number;
}

