/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AcceptPrimarySaleNotImplementedBodyAllOf1
 */
export interface AcceptPrimarySaleNotImplementedBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof AcceptPrimarySaleNotImplementedBodyAllOf1
     */
    'code': AcceptPrimarySaleNotImplementedBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof AcceptPrimarySaleNotImplementedBodyAllOf1
     */
    'details': object | null;
}

export const AcceptPrimarySaleNotImplementedBodyAllOf1CodeEnum = {
    NotImplementedError: 'NOT_IMPLEMENTED_ERROR'
} as const;

export type AcceptPrimarySaleNotImplementedBodyAllOf1CodeEnum = typeof AcceptPrimarySaleNotImplementedBodyAllOf1CodeEnum[keyof typeof AcceptPrimarySaleNotImplementedBodyAllOf1CodeEnum];


