/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AcceptPrimarySaleUnprocessableEntityBodyAllOf1
 */
export interface AcceptPrimarySaleUnprocessableEntityBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof AcceptPrimarySaleUnprocessableEntityBodyAllOf1
     */
    'code': AcceptPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof AcceptPrimarySaleUnprocessableEntityBodyAllOf1
     */
    'details': object | null;
}

export const AcceptPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum = {
    UnprocessableEntityError: 'UNPROCESSABLE_ENTITY_ERROR'
} as const;

export type AcceptPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum = typeof AcceptPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum[keyof typeof AcceptPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum];


