/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContractCreateAPIRequest
 */
export interface ContractCreateAPIRequest {
    /**
     * 
     * @type {string}
     * @memberof ContractCreateAPIRequest
     */
    'contract_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreateAPIRequest
     */
    'data_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractCreateAPIRequest
     */
    'mint_url'?: string;
}

