/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoreEncodeAssetTokenData
 */
export interface CoreEncodeAssetTokenData {
    /**
     * used if token is mintable
     * @type {string}
     * @memberof CoreEncodeAssetTokenData
     */
    'blueprint'?: string;
    /**
     * used if token is mintable
     * @type {string}
     * @memberof CoreEncodeAssetTokenData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CoreEncodeAssetTokenData
     */
    'token_address'?: string;
    /**
     * used if token is non-mintable
     * @type {string}
     * @memberof CoreEncodeAssetTokenData
     */
    'token_id'?: string;
}

