/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePrimarySaleInternalServerErrorBodyAllOf1
 */
export interface CreatePrimarySaleInternalServerErrorBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof CreatePrimarySaleInternalServerErrorBodyAllOf1
     */
    'code': CreatePrimarySaleInternalServerErrorBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof CreatePrimarySaleInternalServerErrorBodyAllOf1
     */
    'details': object | null;
}

export const CreatePrimarySaleInternalServerErrorBodyAllOf1CodeEnum = {
    InternalServerError: 'INTERNAL_SERVER_ERROR'
} as const;

export type CreatePrimarySaleInternalServerErrorBodyAllOf1CodeEnum = typeof CreatePrimarySaleInternalServerErrorBodyAllOf1CodeEnum[keyof typeof CreatePrimarySaleInternalServerErrorBodyAllOf1CodeEnum];


