/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePrimarySaleNotFoundBodyAllOf1
 */
export interface CreatePrimarySaleNotFoundBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof CreatePrimarySaleNotFoundBodyAllOf1
     */
    'code': CreatePrimarySaleNotFoundBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof CreatePrimarySaleNotFoundBodyAllOf1
     */
    'details': object | null;
}

export const CreatePrimarySaleNotFoundBodyAllOf1CodeEnum = {
    ResourceNotFound: 'RESOURCE_NOT_FOUND'
} as const;

export type CreatePrimarySaleNotFoundBodyAllOf1CodeEnum = typeof CreatePrimarySaleNotFoundBodyAllOf1CodeEnum[keyof typeof CreatePrimarySaleNotFoundBodyAllOf1CodeEnum];


