/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreatePrimarySaleInternalServerErrorBodyAllOf0 } from './create-primary-sale-internal-server-error-body-all-of0';
// May contain unused imports in some cases
// @ts-ignore
import { CreatePrimarySaleInternalServerErrorBodyAllOf1 } from './create-primary-sale-internal-server-error-body-all-of1';

/**
 * @type CreatePrimarySaleInternalServerErrorBody
 * @export
 */
export type CreatePrimarySaleInternalServerErrorBody = CreatePrimarySaleInternalServerErrorBodyAllOf0 & CreatePrimarySaleInternalServerErrorBodyAllOf1;


