/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateMetadataRefreshRequest
 */
export interface CreateMetadataRefreshRequest {
    /**
     * The collection contract address
     * @type {string}
     * @memberof CreateMetadataRefreshRequest
     */
    'collection_address': string;
    /**
     * The tokens to refresh
     * @type {Array<string>}
     * @memberof CreateMetadataRefreshRequest
     */
    'token_ids': Array<string>;
}

