/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTransferResponseV2
 */
export interface CreateTransferResponseV2 {
    /**
     * List of transfer IDs
     * @type {Array<number>}
     * @memberof CreateTransferResponseV2
     */
    'transfer_ids': Array<number>;
}

