/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreatePrimarySaleUnauthorizedBodyAllOf0 } from './create-primary-sale-unauthorized-body-all-of0';
// May contain unused imports in some cases
// @ts-ignore
import { CreatePrimarySaleUnauthorizedBodyAllOf1 } from './create-primary-sale-unauthorized-body-all-of1';

/**
 * @type CreatePrimarySaleUnauthorizedBody
 * @export
 */
export type CreatePrimarySaleUnauthorizedBody = CreatePrimarySaleUnauthorizedBodyAllOf0 & CreatePrimarySaleUnauthorizedBodyAllOf1;


