/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePrimarySaleForbiddenBodyAllOf1
 */
export interface CreatePrimarySaleForbiddenBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof CreatePrimarySaleForbiddenBodyAllOf1
     */
    'code': CreatePrimarySaleForbiddenBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof CreatePrimarySaleForbiddenBodyAllOf1
     */
    'details': object | null;
}

export const CreatePrimarySaleForbiddenBodyAllOf1CodeEnum = {
    AuthenticationError: 'AUTHENTICATION_ERROR'
} as const;

export type CreatePrimarySaleForbiddenBodyAllOf1CodeEnum = typeof CreatePrimarySaleForbiddenBodyAllOf1CodeEnum[keyof typeof CreatePrimarySaleForbiddenBodyAllOf1CodeEnum];


