/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EncodeAssetTokenData
 */
export interface EncodeAssetTokenData {
    /**
     * Blueprint information of the token to be encoded. Used if token is mintable.
     * @type {string}
     * @memberof EncodeAssetTokenData
     */
    'blueprint'?: string;
    /**
     * ID of the token to be encoded. Used if token is mintable.
     * @type {string}
     * @memberof EncodeAssetTokenData
     */
    'id'?: string;
    /**
     * Contract address of the token to be encoded
     * @type {string}
     * @memberof EncodeAssetTokenData
     */
    'token_address'?: string;
    /**
     * TokenId of the token to be encoded. Used if token is non-mintable
     * @type {string}
     * @memberof EncodeAssetTokenData
     */
    'token_id'?: string;
}

