/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EncodeAssetResponse
 */
export interface EncodeAssetResponse {
    /**
     * Stark encoded asset id
     * @type {string}
     * @memberof EncodeAssetResponse
     */
    'asset_id': string;
    /**
     * Stark encoded asset type
     * @type {string}
     * @memberof EncodeAssetResponse
     */
    'asset_type': string;
}

