/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1
 */
export interface ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1
     */
    'code': ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1
     */
    'details': object | null;
}

export const ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum = {
    NotImplementedError: 'NOT_IMPLEMENTED_ERROR'
} as const;

export type ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum = typeof ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum[keyof typeof ExperimentalCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum];


