/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SignableTransferDetailsV2 } from './signable-transfer-details-v2';

/**
 * 
 * @export
 * @interface GetSignableTransferRequestV2
 */
export interface GetSignableTransferRequestV2 {
    /**
     * Ethereum address of the transferring user
     * @type {string}
     * @memberof GetSignableTransferRequestV2
     */
    'sender_ether_key': string;
    /**
     * List of signable transfer details
     * @type {Array<SignableTransferDetailsV2>}
     * @memberof GetSignableTransferRequestV2
     */
    'signable_requests': Array<SignableTransferDetailsV2>;
}

