/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSignableTransferResponseV1
 */
export interface GetSignableTransferResponseV1 {
    /**
     * Amount of the asset being transferred
     * @type {string}
     * @memberof GetSignableTransferResponseV1
     */
    'amount': string;
    /**
     * ID of the asset being transferred
     * @type {string}
     * @memberof GetSignableTransferResponseV1
     */
    'asset_id': string;
    /**
     * Token in request to match in SDK implementation
     * @type {number}
     * @memberof GetSignableTransferResponseV1
     */
    'expiration_timestamp': number;
    /**
     * Nonce of the transfer
     * @type {number}
     * @memberof GetSignableTransferResponseV1
     */
    'nonce': number;
    /**
     * Hash of the payload
     * @type {string}
     * @memberof GetSignableTransferResponseV1
     */
    'payload_hash': string;
    /**
     * Receiver of the transfer
     * @type {string}
     * @memberof GetSignableTransferResponseV1
     */
    'receiver_stark_key': string;
    /**
     * ID of the vault being transferred to
     * @type {number}
     * @memberof GetSignableTransferResponseV1
     */
    'receiver_vault_id': number;
    /**
     * Sender of the transfer
     * @type {string}
     * @memberof GetSignableTransferResponseV1
     */
    'sender_stark_key'?: string;
    /**
     * ID of the vault being transferred from
     * @type {number}
     * @memberof GetSignableTransferResponseV1
     */
    'sender_vault_id': number;
    /**
     * Message to sign with L1 wallet to confirm transfer request
     * @type {string}
     * @memberof GetSignableTransferResponseV1
     */
    'signable_message': string;
}

