/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPrimarySaleBadRequestBodyAllOf1
 */
export interface GetPrimarySaleBadRequestBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof GetPrimarySaleBadRequestBodyAllOf1
     */
    'code': GetPrimarySaleBadRequestBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof GetPrimarySaleBadRequestBodyAllOf1
     */
    'details': object | null;
}

export const GetPrimarySaleBadRequestBodyAllOf1CodeEnum = {
    ValidationError: 'VALIDATION_ERROR'
} as const;

export type GetPrimarySaleBadRequestBodyAllOf1CodeEnum = typeof GetPrimarySaleBadRequestBodyAllOf1CodeEnum[keyof typeof GetPrimarySaleBadRequestBodyAllOf1CodeEnum];


