/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSignableRegistrationOffchainResponse
 */
export interface GetSignableRegistrationOffchainResponse {
    /**
     * Hash of the payload to be signed for user registration offchain
     * @type {string}
     * @memberof GetSignableRegistrationOffchainResponse
     */
    'payload_hash': string;
    /**
     * EIP-712 encoding of the StarkEx Register User Offchain request to be displayed to the user
     * @type {string}
     * @memberof GetSignableRegistrationOffchainResponse
     */
    'readable_transaction': string;
    /**
     * Message to sign with L1 wallet to register user offchain
     * @type {string}
     * @memberof GetSignableRegistrationOffchainResponse
     */
    'signable_message': string;
    /**
     * IMX signed readable_transaction and payload_hash
     * @type {string}
     * @memberof GetSignableRegistrationOffchainResponse
     */
    'verification_signature': string;
}

