/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Asset } from './asset';

/**
 * 
 * @export
 * @interface ListAssetsResponse
 */
export interface ListAssetsResponse {
    /**
     * Generated cursor returned by previous query
     * @type {string}
     * @memberof ListAssetsResponse
     */
    'cursor'?: string;
    /**
     * Remaining results flag. 1: there are remaining results matching this query, 0: no remaining results
     * @type {number}
     * @memberof ListAssetsResponse
     */
    'remaining'?: number;
    /**
     * Assets matching query parameters
     * @type {Array<Asset>}
     * @memberof ListAssetsResponse
     */
    'result'?: Array<Asset>;
}

