/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MintTokenDataV2 } from './mint-token-data-v2';

/**
 * 
 * @export
 * @interface MintUser
 */
export interface MintUser {
    /**
     * List of Mint tokens
     * @type {Array<MintTokenDataV2>}
     * @memberof MintUser
     */
    'tokens': Array<MintTokenDataV2>;
    /**
     * User wallet address
     * @type {string}
     * @memberof MintUser
     */
    'user': string;
}

