/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NftprimarytransactionWidgetParams } from './nftprimarytransaction-widget-params';

/**
 * 
 * @export
 * @interface NftprimarytransactionCreateAPIRequest
 */
export interface NftprimarytransactionCreateAPIRequest {
    /**
     * Contract address of the asset to be created
     * @type {string}
     * @memberof NftprimarytransactionCreateAPIRequest
     */
    'contract_address'?: string;
    /**
     * Temporary asset id
     * @type {string}
     * @memberof NftprimarytransactionCreateAPIRequest
     */
    'offer_id'?: string;
    /**
     * Provider name
     * @type {string}
     * @memberof NftprimarytransactionCreateAPIRequest
     */
    'provider'?: string;
    /**
     * Ethereum address of the user who wants to create transaction
     * @type {string}
     * @memberof NftprimarytransactionCreateAPIRequest
     */
    'user_wallet_address'?: string;
    /**
     * 
     * @type {NftprimarytransactionWidgetParams}
     * @memberof NftprimarytransactionCreateAPIRequest
     */
    'widget'?: NftprimarytransactionWidgetParams;
}

