/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NftprimarytransactionCreateResponse
 */
export interface NftprimarytransactionCreateResponse {
    /**
     * Contract address of the asset to be created
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'contract_address'?: string;
    /**
     * Temporary asset id
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'offer_id'?: string;
    /**
     * Provider name
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'provider'?: string;
    /**
     * Ethereum address of the seller
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'seller_wallet_address'?: string;
    /**
     * Asset id
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'token_id'?: string;
    /**
     * Transaction id
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'transaction_id'?: string;
    /**
     * Widget Url signed by provider
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'url'?: string;
    /**
     * Ethereum address of the user who wants to create transaction
     * @type {string}
     * @memberof NftprimarytransactionCreateResponse
     */
    'user_wallet_address'?: string;
}

