/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NftsecondarytransactionWidgetParams } from './nftsecondarytransaction-widget-params';

/**
 * 
 * @export
 * @interface NftsecondarytransactionCreateAPIRequest
 */
export interface NftsecondarytransactionCreateAPIRequest {
    /**
     * 
     * @type {number}
     * @memberof NftsecondarytransactionCreateAPIRequest
     */
    'order_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionCreateAPIRequest
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionCreateAPIRequest
     */
    'user_wallet_address'?: string;
    /**
     * 
     * @type {NftsecondarytransactionWidgetParams}
     * @memberof NftsecondarytransactionCreateAPIRequest
     */
    'widget'?: NftsecondarytransactionWidgetParams;
}

