/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NftsecondarytransactionGetTransactionResponse
 */
export interface NftsecondarytransactionGetTransactionResponse {
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'order_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'provider'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'token_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'token_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'transaction_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof NftsecondarytransactionGetTransactionResponse
     */
    'user_wallet_address'?: string;
}

