/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderFeeInfo } from './order-fee-info';
// May contain unused imports in some cases
// @ts-ignore
import { OrdersMakerTakerFee } from './orders-maker-taker-fee';

/**
 * @type OrderV3MakerFees
 * MakerFees is the information about the fees that needs to be paid by the maker (liquidity)
 * @export
 */
export type OrderV3MakerFees = OrdersMakerTakerFee;


