/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RejectPrimarySaleNotFoundBodyAllOf1
 */
export interface RejectPrimarySaleNotFoundBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof RejectPrimarySaleNotFoundBodyAllOf1
     */
    'code': RejectPrimarySaleNotFoundBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof RejectPrimarySaleNotFoundBodyAllOf1
     */
    'details': object | null;
}

export const RejectPrimarySaleNotFoundBodyAllOf1CodeEnum = {
    ResourceNotFound: 'RESOURCE_NOT_FOUND'
} as const;

export type RejectPrimarySaleNotFoundBodyAllOf1CodeEnum = typeof RejectPrimarySaleNotFoundBodyAllOf1CodeEnum[keyof typeof RejectPrimarySaleNotFoundBodyAllOf1CodeEnum];


