/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RejectPrimarySaleNotImplementedBodyAllOf0 } from './reject-primary-sale-not-implemented-body-all-of0';
// May contain unused imports in some cases
// @ts-ignore
import { RejectPrimarySaleNotImplementedBodyAllOf1 } from './reject-primary-sale-not-implemented-body-all-of1';

/**
 * @type RejectPrimarySaleNotImplementedBody
 * @export
 */
export type RejectPrimarySaleNotImplementedBody = RejectPrimarySaleNotImplementedBodyAllOf0 & RejectPrimarySaleNotImplementedBodyAllOf1;


