/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RejectPrimarySaleInternalServerErrorBodyAllOf1
 */
export interface RejectPrimarySaleInternalServerErrorBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof RejectPrimarySaleInternalServerErrorBodyAllOf1
     */
    'code': RejectPrimarySaleInternalServerErrorBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof RejectPrimarySaleInternalServerErrorBodyAllOf1
     */
    'details': object | null;
}

export const RejectPrimarySaleInternalServerErrorBodyAllOf1CodeEnum = {
    InternalServerError: 'INTERNAL_SERVER_ERROR'
} as const;

export type RejectPrimarySaleInternalServerErrorBodyAllOf1CodeEnum = typeof RejectPrimarySaleInternalServerErrorBodyAllOf1CodeEnum[keyof typeof RejectPrimarySaleInternalServerErrorBodyAllOf1CodeEnum];


