/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RejectPrimarySaleUnprocessableEntityBodyAllOf1
 */
export interface RejectPrimarySaleUnprocessableEntityBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof RejectPrimarySaleUnprocessableEntityBodyAllOf1
     */
    'code': RejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof RejectPrimarySaleUnprocessableEntityBodyAllOf1
     */
    'details': object | null;
}

export const RejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum = {
    UnprocessableEntityError: 'UNPROCESSABLE_ENTITY_ERROR'
} as const;

export type RejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum = typeof RejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum[keyof typeof RejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum];


