/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SignableTransferDetailsV2Token } from './signable-transfer-details-v2-token';

/**
 * 
 * @export
 * @interface SignableTransferDetailsV2
 */
export interface SignableTransferDetailsV2 {
    /**
     * Amount of the token to transfer
     * @type {string}
     * @memberof SignableTransferDetailsV2
     */
    'amount': string;
    /**
     * Ethereum address of the receiving user
     * @type {string}
     * @memberof SignableTransferDetailsV2
     */
    'receiver': string;
    /**
     * 
     * @type {SignableTransferDetailsV2Token}
     * @memberof SignableTransferDetailsV2
     */
    'token': SignableTransferDetailsV2Token;
}

