/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableRejectPrimarySaleNotImplementedBodyAllOf1
 */
export interface SignableRejectPrimarySaleNotImplementedBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof SignableRejectPrimarySaleNotImplementedBodyAllOf1
     */
    'code': SignableRejectPrimarySaleNotImplementedBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof SignableRejectPrimarySaleNotImplementedBodyAllOf1
     */
    'details': object | null;
}

export const SignableRejectPrimarySaleNotImplementedBodyAllOf1CodeEnum = {
    NotImplementedError: 'NOT_IMPLEMENTED_ERROR'
} as const;

export type SignableRejectPrimarySaleNotImplementedBodyAllOf1CodeEnum = typeof SignableRejectPrimarySaleNotImplementedBodyAllOf1CodeEnum[keyof typeof SignableRejectPrimarySaleNotImplementedBodyAllOf1CodeEnum];


