/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SignableToken } from './signable-token';

/**
 * 
 * @export
 * @interface SignableTransferDetails
 */
export interface SignableTransferDetails {
    /**
     * Amount of the token to transfer
     * @type {string}
     * @memberof SignableTransferDetails
     */
    'amount': string;
    /**
     * Ethereum address of the receiving user
     * @type {string}
     * @memberof SignableTransferDetails
     */
    'receiver': string;
    /**
     * 
     * @type {SignableToken}
     * @memberof SignableTransferDetails
     */
    'token': SignableToken;
}

