/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableCreatePrimarySaleNotImplementedBodyAllOf1
 */
export interface SignableCreatePrimarySaleNotImplementedBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof SignableCreatePrimarySaleNotImplementedBodyAllOf1
     */
    'code': SignableCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof SignableCreatePrimarySaleNotImplementedBodyAllOf1
     */
    'details': object | null;
}

export const SignableCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum = {
    NotImplementedError: 'NOT_IMPLEMENTED_ERROR'
} as const;

export type SignableCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum = typeof SignableCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum[keyof typeof SignableCreatePrimarySaleNotImplementedBodyAllOf1CodeEnum];


