/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SignableRejectPrimarySaleUnprocessableEntityBodyAllOf0 } from './signable-reject-primary-sale-unprocessable-entity-body-all-of0';
// May contain unused imports in some cases
// @ts-ignore
import { SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1 } from './signable-reject-primary-sale-unprocessable-entity-body-all-of1';

/**
 * @type SignableRejectPrimarySaleUnprocessableEntityBody
 * @export
 */
export type SignableRejectPrimarySaleUnprocessableEntityBody = SignableRejectPrimarySaleUnprocessableEntityBodyAllOf0 & SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1;


