/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableToken
 */
export interface SignableToken {
    /**
     * Token data. See https://docs.x.immutable.com/docs/token-data-object
     * @type {object}
     * @memberof SignableToken
     */
    'data'?: object;
    /**
     * Type of token
     * @type {string}
     * @memberof SignableToken
     */
    'type'?: string;
}

