/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableAcceptPrimarySaleUnprocessableEntityBodyAllOf0
 */
export interface SignableAcceptPrimarySaleUnprocessableEntityBodyAllOf0 {
    /**
     * Link to IMX documentation that can help resolve this error
     * @type {string}
     * @memberof SignableAcceptPrimarySaleUnprocessableEntityBodyAllOf0
     */
    'link': string;
    /**
     * Error Message
     * @type {string}
     * @memberof SignableAcceptPrimarySaleUnprocessableEntityBodyAllOf0
     */
    'message': string;
    /**
     * Trace ID of the initial request
     * @type {string}
     * @memberof SignableAcceptPrimarySaleUnprocessableEntityBodyAllOf0
     */
    'trace_id': string;
}

