/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1
 */
export interface SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1
     */
    'code': SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1
     */
    'details': object | null;
}

export const SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum = {
    UnprocessableEntityError: 'UNPROCESSABLE_ENTITY_ERROR'
} as const;

export type SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum = typeof SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum[keyof typeof SignableRejectPrimarySaleUnprocessableEntityBodyAllOf1CodeEnum];


