/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SignableCreatePrimarySaleParamsBodyFeesItems } from './signable-create-primary-sale-params-body-fees-items';

/**
 * 
 * @export
 * @interface SignableCreatePrimarySaleParamsBody
 */
export interface SignableCreatePrimarySaleParamsBody {
    /**
     * Ethereum address of the payer of the primary sale
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'buyer_ether_key': string;
    /**
     * Time the primary sale expires
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'expiration_timestamp'?: string;
    /**
     * 
     * @type {Array<SignableCreatePrimarySaleParamsBodyFeesItems>}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'fees'?: Array<SignableCreatePrimarySaleParamsBodyFeesItems>;
    /**
     * Ethereum address of the recipient of the items - in many cases this will be the same as account, but sometimes you may wish to gift the items to another address.
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'items_recipient_ether_key': string;
    /**
     * Fee exclusive amount of the primary sale
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'payment_amount': string;
    /**
     * Ethereum address of the recipient of the sale proceedings
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'payment_recipient_ether_key': string;
    /**
     * 
     * @type {object}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'payment_token': object;
    /**
     * Arbitrary data defined by the selling party (e.g. game studio) to identify the primary sale. We suggest signing this payload to verify authenticity when processing.
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'studio_data': string;
    /**
     * Ethereum address of the studio operating the primary sale, will be used to verify in completion
     * @type {string}
     * @memberof SignableCreatePrimarySaleParamsBody
     */
    'studio_ether_key': string;
}

