/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SignableAcceptPrimarySaleInternalServerErrorBodyAllOf0 } from './signable-accept-primary-sale-internal-server-error-body-all-of0';
// May contain unused imports in some cases
// @ts-ignore
import { SignableAcceptPrimarySaleInternalServerErrorBodyAllOf1 } from './signable-accept-primary-sale-internal-server-error-body-all-of1';

/**
 * @type SignableAcceptPrimarySaleInternalServerErrorBody
 * @export
 */
export type SignableAcceptPrimarySaleInternalServerErrorBody = SignableAcceptPrimarySaleInternalServerErrorBodyAllOf0 & SignableAcceptPrimarySaleInternalServerErrorBodyAllOf1;


