/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * Immutable X API
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableAcceptPrimarySaleBadRequestBodyAllOf1
 */
export interface SignableAcceptPrimarySaleBadRequestBodyAllOf1 {
    /**
     * Error Code
     * @type {string}
     * @memberof SignableAcceptPrimarySaleBadRequestBodyAllOf1
     */
    'code': SignableAcceptPrimarySaleBadRequestBodyAllOf1CodeEnum;
    /**
     * Additional details to help resolve the error
     * @type {object}
     * @memberof SignableAcceptPrimarySaleBadRequestBodyAllOf1
     */
    'details': object | null;
}

export const SignableAcceptPrimarySaleBadRequestBodyAllOf1CodeEnum = {
    ValidationError: 'VALIDATION_ERROR'
} as const;

export type SignableAcceptPrimarySaleBadRequestBodyAllOf1CodeEnum = typeof SignableAcceptPrimarySaleBadRequestBodyAllOf1CodeEnum[keyof typeof SignableAcceptPrimarySaleBadRequestBodyAllOf1CodeEnum];


