/* tslint:disable */
/* eslint-disable */
/**
 * Immutable X API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@immutable.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignableCreatePrimarySaleOKBodyFeeInfo
 */
export interface SignableCreatePrimarySaleOKBodyFeeInfo {
    /**
     * Asset ID of fee token
     * @type {string}
     * @memberof SignableCreatePrimarySaleOKBodyFeeInfo
     */
    'asset_id'?: string;
    /**
     * Fee limit of transaction - total fee amount
     * @type {string}
     * @memberof SignableCreatePrimarySaleOKBodyFeeInfo
     */
    'fee_limit'?: string;
    /**
     * Vault ID of fee payer
     * @type {number}
     * @memberof SignableCreatePrimarySaleOKBodyFeeInfo
     */
    'source_vault_id'?: number;
}

